services:
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: ovs-rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}'
    ports:
      - '5672'